Adding pointer and some focus events
Pauan/rust-dominator pull request #59
Opened 2022-03-10 18:16 UTC by MendyBerger

This pr adds the following:

- Pointer events
- `FocusIn`/`Out` evnets
- `FocusEvent.related_target`

2022-03-12 04:46 UTC, Pauan requested changes

2022-03-12 04:46 UTC, Pauan commented on src/events.rs
> +            #[inline] pub fn width(&self) -> i32 { self.event.width() }
Although this is called `width` in the DOM, I wonder if that's the best name.

Maybe it should be renamed to `pointer_width`, to make it more clear what it's doing?

2022-03-12 04:46 UTC, Pauan commented on src/events.rs
> +            #[inline] pub fn height(&self) -> i32 { self.event.height() }
Same thing as for `width`

2022-03-12 04:46 UTC, Pauan commented on src/events.rs
> +            #[inline] pub fn pointer_type(&self) -> String { self.event.pointer_type() }
This should probably return an enum. Since web-sys doesn't return an enum, maybe we should leave this out for now.

2022-03-13 02:35 UTC, MendyBerger commented
@Pauan updated pr

2022-03-13 02:39 UTC, Pauan approved these changes
Thanks!

2022-03-13 02:39 UTC, merged